### ISSUE TITLE
Undefined name 'WordCloud' and 'ImageColorGenerator'

### ISSUE THREAD

**Issue by cclauss** [chihaiyishen/-Python#2]
flake8 testing of https://github.com/chihaiyishen/Python-Learning on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./python 爬虫/wechat/demo.py:68:20: F821 undefined name 'WordCloud'
    my_wordcloud = WordCloud(background_color="white", max_words=2000,
                   ^
./python 爬虫/wechat/demo.py:71:20: F821 undefined name 'ImageColorGenerator'
    image_colors = ImageColorGenerator(coloring)
                   ^
2     F821 undefined name 'WordCloud'
2
```

**Comment by RidingRoad** [comment]
1.第一个提示没有WordCloud,很有可能是本地没有安装WordCloud模块或者使用import WordCloud来引入,那么需要在引用函数前需要加上模块名,WordCloud.WordCloud()
2.安装WordCloud, pip3 install WordCloud
3.第二个错误检查一下是否导入包的的方式,试试在前面加上模块名
